server:
  port: 9000
  servlet:
    context-path: /pay

spring:
  thymeleaf:
    cache: false
  application:
    name: micr-pay

dubbo:
  application:
    name: micr-pay-kq
    id: micr-pay-kq
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernode.pay
  consumer:
    timeout: 30000
    retries: 0
    check: false
  protocol:
    port: 20886
    name: dubbo